site_name: Yocto Playground
site_url: https://gauravagarwalgarg.github.io/yocto-playground/
repo_url: https://github.com/GauravAgarwalGarg/yocto-playground
theme:
  name: material
  palette:
    - scheme: slate
  features:
    - navigation.sections
    - content.code.copy
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - tables
  - toc:
      permalink: true
