# Layer configuration for meta-auton
# Custom BSP + distro layer for embedded Linux targets

BBPATH .= ":${LAYERDIR}"

BBFILES += " \
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "meta-auton"
BBFILE_PATTERN_meta-auton = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-auton = "10"

LAYERDEPENDS_meta-auton = "core"
LAYERSERIES_COMPAT_meta-auton = "scarthgap styhead walnascar"
