#@TYPE: Machine
#@NAME: BeagleBone Black
#@DESCRIPTION: Machine configuration for BeagleBone Black (AM335x)

require conf/machine/include/ti-soc.inc

SOC_FAMILY = "ti-am335x"
DEFAULTTUNE = "cortexa8hf-neon"
require conf/machine/include/arm/armv7a/tune-cortexa8.inc

PREFERRED_PROVIDER_virtual/kernel = "linux-auton"
PREFERRED_VERSION_linux-auton = "6.12%"

KERNEL_IMAGETYPE = "zImage"
KERNEL_DEVICETREE = "am335x-boneblack.dtb"

UBOOT_MACHINE = "am335x_evm_defconfig"
SPL_BINARY = "MLO"
UBOOT_SUFFIX = "img"

MACHINE_FEATURES = "usbgadget usbhost vfat ext2 screen alsa ethernet wifi"
MACHINE_EXTRA_RRECOMMENDS = "kernel-modules kernel-devicetree"

SERIAL_CONSOLES = "115200;ttyS0"
IMAGE_FSTYPES = "tar.xz wic wic.bmap"
WKS_FILE = "beaglebone-yocto.wks"
