#@TYPE: Machine
#@NAME: Raspberry Pi 5
#@DESCRIPTION: Machine configuration for Raspberry Pi 5 (BCM2712)

DEFAULTTUNE = "cortexa76"
require conf/machine/include/arm/armv8-2a/tune-cortexa76.inc

PREFERRED_PROVIDER_virtual/kernel = "linux-auton"
PREFERRED_VERSION_linux-auton = "6.12%"

KERNEL_IMAGETYPE = "Image"
KERNEL_DEVICETREE = "broadcom/bcm2712-rpi-5-b.dtb"

UBOOT_MACHINE = "rpi_arm64_defconfig"

RPI_USE_U_BOOT = "1"
ENABLE_UART = "1"
DISABLE_OVERSCAN = "1"

MACHINE_FEATURES = "usbhost wifi bluetooth alsa screen ethernet"
MACHINE_EXTRA_RRECOMMENDS = "kernel-modules kernel-devicetree linux-firmware-rpidistro-bcm43455"

SERIAL_CONSOLES = "115200;ttyAMA10"
IMAGE_FSTYPES = "tar.xz rpi-sdimg wic wic.bmap"
